### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by sideloading** [vanyasem/VK-Scraper#8]
Hi,

I am getting an IndexError issue using the latest version. 
Python 3.6.6 via pyenv, Debian 10

Command: `vk-scraper user -u "usernam.e@mail.com" -p "pass"`

```
Traceback (most recent call last):
  File "/home/sideloading/.local/bin/vk-scraper", line 11, in <module>
    load_entry_point('VK-Scraper==2.0.3', 'console_scripts', 'vk-scraper')()
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_scraper/app.py", line 492, in main
    scraper.scrape()
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_scraper/app.py", line 155, in scrape
    self.login()
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_scraper/app.py", line 92, in login
    self.vk_session.auth()
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_api/vk_api.py", line 177, in auth
    self._auth_cookies(reauth=reauth)
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_api/vk_api.py", line 208, in _auth_cookies
    self._api_login()
  File "/home/sideloading/.local/lib/python3.6/site-packages/vk_api/vk_api.py", line 439, in _api_login
    params = response.url.split('#', 1)[1].split('&')
IndexError: list index out of range
```

**Comment by r3dnck** [comment]
@sideloading Update vk_api to the latest version

**Comment by sideloading** [comment]
@r3dnck thank you!
